export enum ContactMethod {
  WHATSAPP = "WHATSAPP",
  EMAIL = "EMAIL",
  IMO = "IMO",
  TELEGRAM = "TELEGRAM",
}

/**
 *
 * Supplier Related Enums
 *
 */

export enum SupplierRole {
  NONE = "NONE",
  SALES_MAN = "SALES_MAN",
  OWNER = "OWNER",
  DISTRIBUTOR = "DISTRIBUTOR",
  DEALER = "DEALER",
  WHOLESALER = "WHOLESALER",
  RETAILER = "RETAILER",
  MANUFACTURER = "MANUFACTURER",
  IMPORTER = "IMPORTER",
  REPRESENTATIVE = "REPRESENTATIVE",
}

export enum SupplierType {
  MEDICINE = "MEDICINE",
  FEED = "FEED",
  HUSK = "HUSK",
  HARDWARE = "HARDWARE",
  MEDICAL_EQUIPMENT = "MEDICAL_EQUIPMENT",
  LAB_EQUIPMENT = "LAB_EQUIPMENT",
  OFFICE_SUPPLIES = "OFFICE_SUPPLIES",
  CLEANING_SUPPLIES = "CLEANING_SUPPLIES",
  IT_HARDWARE = "IT_HARDWARE",
  SOFTWARE = "SOFTWARE",
  IT_EQUEPMENT = "IT_EQUEPMENT",
  INTERNET = "INTERNET",
  ELECTRICAL_EQUIPMENT = "ELECTRICAL_EQUIPMENT",
  OTHER = "OTHER",
  NONE = "NONE",
}

/**
 *
 * Employee Related Enums
 *
 */

export enum EmployeeRole {
  WORKER = "WORKER",
  MANAGER = "MANAGER",
  INTERN = "INTERN",
  NONE = "NONE",
}

export enum BirdBreed {
  CLASSIC = "CLASSIC",
  HIBREED = "HIBREED",
  PAKISTHANI = "PAKISTHANI",
  KEDERNATH = "KEDERNATH",
  FAOMI = "FAOMI",
  TIGER = "TIGER",
}
